[workspace]
authors = ["Rohit Goswami <rohit.goswami@epfl.ch>"]
channels = ["metatensor", "conda-forge", "https://repo.prefix.dev/rg-forge", "bioconda"]
name = "metatensor_ecosystem_paper_plumed"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
uv = ">=0.8.4,<0.9"

[pypi-dependencies]
metatrain = ">=2025.8.1, <2026"
metatensor-torch = ">=0.7.6, <0.8"
metatomic-torch = ">=0.1.3, <0.2"
ase = ">=3.25.0, <4"
rgpycrumbs = { git = "https://github.com/HaoZeke/rgpycrumbs.git", rev = "eb5ef9b6e08606e36b8732b5ed0baf3f1443d4d4" }

[feature.plumed.pypi-dependencies]
chemiscope = ">=0.8.6, <0.9"
cmcrameri = ">=1.9, <2"

[feature.plumed.dependencies]
lammps-metatomic = { version = "*", build = "*openmpi*" }
plumed-metatomic = { version = "*", build = "*openmpi*" }
pandas = ">=2.3.1,<3"
rich = ">=14.1.0,<15"
scikit-learn = ">=1.7.2,<2"

[environments]
plumed = {features = ["plumed"]}
